fsi_web:
    resource: "@FSiWebBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@FSiAdminBundle/Resources/config/routing/admin.yml"
    prefix: /admin

admin_security:
      resource: "@FSiAdminSecurityBundle/Resources/config/routing/admin_security.yml"
      prefix: /admin

