security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_panel:
            pattern:    ^/admin
            form_login:
                default_target_path: fsi_admin
                provider: fos_userbundle
                check_path: fsi_admin_security_user_check
                login_path: fsi_admin_security_user_login
            logout:
                path:   fsi_admin_security_user_logout
            anonymous:    ~

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }